language: generic
sudo: required
dist: trusty

addons:
  apt:
    sources: &commonsources
    packages: &commonpackages
    - cmake
    - cmake-data

before_script:
    - git clone --branch ${DUNE_BRANCH} --depth 1 https://gitlab.dune-project.org/core/dune-common.git
    - git clone --depth 1 https://github.com/wwu-numerik/dune-demos-bin.git local/bin
    - sudo -E apt-get build-dep libdune-common-2.2.1 -y
script:
    - set -e
    - |
        for i in $(git ls-files | \grep -Ev "README|.travis.yml") ; do
            echo "checking ${i}"
            bash ${i}
            OPTS=${i} ./local/bin/build_dune_modules.py
        done

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  except:
    - gh-pages

matrix:
    include:
    - env: DUNE_BRANCH=master
    - env: DUNE_BRANCH=releases/2.3
    - env: DUNE_BRANCH=releases/2.4
